version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - zip -r code.zip.
  post_build:
    commands:
      - aws lambda update-function-code --function-name demo --zip-file fileb://code.zip
      - aws lambda publish-version --function-name demo --description "Automated version"
artifacts:
  files:
    - code.zip
