version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing zip utility..."
      - apt-get update && apt-get install -y zip
  build:
    commands:
      - echo "Listing directory contents..."
      - ls -al
      - echo "Creating zip file..."
      - zip -r code.zip .
  post_build:
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name demo --zip-file fileb://code.zip
      - echo "Publishing new Lambda version..."
      - aws lambda publish-version --function-name demo --description "Automated version update"
artifacts:
  files:
    - code.zip
