version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
      
    commands:
      - echo "Installing build tools..."
      - apt-get update
      - apt-get install -y build-essential

      
  # pre_build:
    #commands:
     # - echo "Installing dependencies..."
      #- npm install --verbose
  build:
    commands:
      - echo "Creating zip file..."
      - zip -r test.zip.
  post_build:
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name demo --zip-file fileb://test.zip
      - echo "Publishing new Lambda version..."
      - aws lambda publish-version --function-name demo --description "Automated version update"
artifacts:
  files:
    - test.zip
